server:
  port: 8085

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %5p [traceID=%X{X-B3-TraceId},spanID=%X{X-B3-SpanId}] %clr(${PID:- }){magenta} %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"